# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    scottlin_pricecrawler.discountparsing.class: ScottLin\PriceCrawlerBundle\Service\DiscountParsing

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    scottlin_pricecrawler.discountparsing:
        class: %scottlin_pricecrawler.discountparsing.class%
